pipeline:
  name: "Demo"

  # Shaders
  shaders:
    - module: "shader.vert"
      stage: "vertex"
    - module: "shader.frag"
      stage: "fragment"

  # Blending Mode
  blending: "None"

  # Formats
  color_format: "VK_FORMAT_R8G8B8A8_UNORM"
  depth_format: "VK_FORMAT_D32_SFLOAT"

  # Multi-sampling
  multisampling: "VK_SAMPLE_COUNT_1_BIT"

  # Rasterization and Culling
  polygon_mode: "fill"
  cull_mode: "back"
  front_face: "clockwise"

  # Input Topology
  topology: "triangle-list"

  # Depth Information
  depth_info:
    depth_test: true
    write_depth: true
    compare_op: "VK_COMPARE_OP_LESS"

  # Descriptor Layouts
  descriptor_layouts:
    - "demoDescriptors.yaml"

  # Push Constants
  push_constants:
    - stages: ["vertex", "fragment"]
      size: 64
      offset: 0
    - stages: ["vertex"]
      size: 64
      offset: 64

