pipeline:
  name: "Skybox"

  # Shaders
  shaders:
    - module: "shader.vert"
      stage: "vertex"
    - module: "shader.frag"
      stage: "fragment"

  # Blending Mode
  blending: "None"

  # Formats
  color_format: "VK_FORMAT_R16G16B16A16_SFLOAT"
  depth_format: "VK_FORMAT_D32_SFLOAT"

  # Multi-sampling
  multisampling: "VK_SAMPLE_COUNT_1_BIT"

  # Rasterization and Culling
  polygon_mode: "fill"
  cull_mode: "none"
  front_face: "clockwise"

  # Input Topology
  topology: "triangle-list"

  # Depth Information
  depth_info:
    depth_test: false
    write_depth: false
    compare_op: "VK_COMPARE_OP_LESS"

  # Vertex Information
  vertex_input:
    bindings:
      - binding: 0
        stride: 32
        input_rate: "vertex"

    attributes:
      - location: 0
        binding: 0
        format: "VK_FORMAT_R32G32B32_SFLOAT"
        offset: 0

  # Descriptor Layouts
  descriptor_layouts:
    - layout: "skyboxDescriptors.yaml"
      set: 0

  # Push Constants
  push_constants:
    - stages: ["vertex"]
      size: 64                  # viewProj matrix (mat4)
      offset: 0

